"""
ADD SOME ADDITIONAL CONSTANTS FOR TESTING
"""


from src.constants import *
DIR_FORMAT_INVALID="{model_username}/{responsetype}/{mediatype2}/"
DIR_FORMAT_ALLVALID="{model_username}{date}{responsetype}{mediatype}{value}{model_id}{first_letter}{sitename}{model_username}"
DIR_FORMAT_ALLWTHINVALID="{invalid}{model_username}{date}{responsetype}{mediatype}{value}{model_id}{first_letter}{sitename}{model_username}"
INVALID_WINDOWS="?{model_username}"
INVALID_LINUX="\0{model_username}"
DATE_VALID="MM-DD-YYYY"
DATE_SILLY="MMRR"
DATE_INVALID="G$"
FILE_VALID="{model_username}{date}{responsetype}{mediatype}{value}{model_id}\
    {first_letter}{sitename},{model_username}{value}{post_id}{filename}{text}{ext}"
FILE_ALLVALIDWTHINVALID="{invalid}{model_username}{date}{responsetype}{mediatype}{value}{model_id}\
    {first_letter}{sitename},{model_username}{value}{post_id}{filename}{text}{ext},{first_letter},{sitename},{model_username}"
METADATA_INVALID= "{model_username}/{responsetype}/{mediatype2}/"
METADATA_ALLVALID="{sitename}{first_letter}{model_username}{model_id}{configpath}{profile}"
METADATA_ALLWTHINVALID="{invalid}{sitename}{first_letter}{model_username}{model_id}{configpath}{profile}"
METADATA_DC="/root/{model_username}/metadata/"
INVALID_JSON='{"auth": {"username": "ddd", "cookie": "auth_id=ddddd; sess=ddddddddddd; auth_hash=; auth_uniq_dds=; auth_uid_ddds=;", \
    "user_agent": "ffffffff6",\
    "x_bc": "ffffffffff", "support_2fa": true, "active": true, "email": "", "password": "", "hashed": false'
VALID_JSON='{"auth": {"username": "ddd", "cookie": "auth_id=ddddd; sess=ddddddddddd; auth_hash=; auth_uniq_dds=; auth_uid_ddds=;", \
    "user_agent": "ffffffff6",\
    "x_bc": "ffffffffff", "support_2fa": true, "active": true, "email": "", "password": "", "hashed": false}}'

INVALID_NAME="00Ayd^&"
VALID_NAME="ADddad99__Y"
WINDOWS_LONGPATH="unittestmockprovidesacore/Mockclassremovingtheneedtocreateahostofstubsthroughout/yourtestsuiteAfterperforminganactionyoucanmakeassertionsaboutwhichmethods/attributeswereusedandargumentstheywerecalledwithYoucanalsospecifyreturnvaluesandsetneededattributesinthenormalway.mkv"
LINUX_LONGPATH="unittestmockprovidesacore/Mockclassremovingtheneedtocreateahostofstubsthroughout/yourtestsuiteAfterperforminganactionyoucanmakeassertionsaboutwhichmethattributeswereusedandargumentstheywerecalledwithYoucanalsospecifyreturnvaluesandsetneededattributesinthenormalway \
                            attributeswereusedandargumentstheywerecalledwithYoucanalsospecifyreturnvaluesandsetneededattributesinthenormalway \
                            attributeswereusedandargumentstheywerecalledwithYoucanalsospecifyreturnvaluesandsetneededattributesinthenormalway \
                            attributeswereusedandargumentstheywerecalledwithYoucanalsospecifyreturnvaluesandsetneededattributesinthenormalway \
                            attributeswereusedandargumentstheywerecalledwithYoucanalsospecifyreturnvaluesandsetneededattributesinthenormalway.mkv"

TIMELINE_EXAMPLE={'responseType': 'post', 'id': 89898, 'postedAt': '2021-02-21T00:53:47+00:00', 'postedAtPrecise': '1613868827.000000', 'expiredAt': None, 'author': {'id': 89898, '_view': 'a'}, 'text': 'throwback nudes to when i had purple hair 😌 the one on the left got viral on reddit 😳', 'rawText': 'throwback nudes to when i had purple hair 😌 the one on the left got viral on reddit 😳', 'lockedText': False, 'isFavorite': False, 'canReport': True, 'canDelete': False, 'canComment': True, 'canEdit': False, 'isPinned': False, 'favoritesCount': 60, 'mediaCount': 2, 'isMediaReady': True, 'voting': [], 'isOpened': True, 'canToggleFavorite': True, 'streamId': None, 'price': None, 'hasVoting': False, 'isAddedToBookmarks': False, 'isArchived': False, 'isPrivateArchived': False, 'isDeleted': False, 'hasUrl': False, 'isCouplePeopleMedia': False, 'commentsCount': 0, 'mentionedUsers': [], 'linkedUsers': [], 'linkedPosts': [], 'tipsAmount': '$0', 'tipsAmountRaw': 0, 'media': [{'id': 89898, 'type': 'photo', 'convertedToVideo': False, 'canView': True, 'hasError': False, 'createdAt': '2021-02-21T00:53:47+00:00', 'info': {'source': {'source': 'https://url.com', 'width': 2320, 'height': 3088, 'size': 0, 'duration': 0}, 'preview': {'width': 960, 'height': 1278, 'size': 0}}, 'source': {'source': 'https://url.com', 'width': 2320, 'height': 3088, 'size': 0, 'duration': 0}, 'squarePreview': 'https://url.com', 'full': 'https://url.com', 'preview': 'https://url.com', 'thumb': 'https://url.com', 'files': {'preview': {'url': 'https://url.com'}}, 'videoSources': {'720': None, '240': None}}, {'id': 89898, 'type': 'photo', 'convertedToVideo': False, 'canView': True, 'hasError': False, 'createdAt': '2021-02-21T00:53:47+00:00', 'info': {'source': {'source': 'https://url.com', 'width': 676, 'height': 900, 'size': 0, 'duration': 0}, 'preview': {'width': 676, 'height': 900, 'size': 0}}, 'source': {'source': 'https://url.com', 'width': 676, 'height': 900, 'size': 0, 'duration': 0}, 'squarePreview': 'https://url.com', 'full': 'https://url.com', 'preview': 'https://url.com', 'thumb': 'https://url.com', 'files': {'preview': {'url': 'https://url.com'}}, 'videoSources': {'720': None, '240': None}}], 'canViewMedia': True, 'preview': []}
PINNED_POSTS_EXAMPLE={'responseType': 'post', 'id': 89898, 'postedAt': '2023-02-25T09:29:24+00:00', 'postedAtPrecise': '1677317364.000000', 'expiredAt': None, 'author': {'id': 89898, '_view': 'a'}, 'text': "date me? 🥺 👉👈<br /> for 20 minutes i'm all yours! tip $39.99<br /> date includes 🌹 ***my full attention,<br /> free rating, free nudes, free video,<br /> 50% off sexting*** and ***50% off my PPVs*** <br /> **and a free sexy surprise just for ur dick** 😈", 'rawText': "date me? 🥺 👉👈\nfor 20 minutes i'm all yours! tip $39.99\ndate includes 🌹 ***my full attention,\nfree rating, free nudes, free video,\n50% off sexting*** and ***50% off my PPVs*** \n**and a free sexy surprise just for ur dick** 😈", 'lockedText': False, 'isFavorite': False, 'canReport': True, 'canDelete': False, 'canComment': True, 'canEdit': False, 'isPinned': True, 'favoritesCount': 60, 'mediaCount': 1, 'isMediaReady': True, 'voting': [], 'isOpened': True, 'canToggleFavorite': True, 'streamId': None, 'price': None, 'hasVoting': False, 'isAddedToBookmarks': False, 'isArchived': False, 'isPrivateArchived': False, 'isDeleted': False, 'hasUrl': False, 'isCouplePeopleMedia': False, 'commentsCount': 1, 'mentionedUsers': [], 'linkedUsers': [], 'linkedPosts': [], 'tipsAmount': '$79.98', 'tipsAmountRaw': 79.98, 'media': [{'id': 89898, 'type': 'photo', 'convertedToVideo': False, 'canView': True, 'hasError': False, 'createdAt': '2023-02-25T09:27:34+00:00', 'info': {'source': {'source': 'https://url.com', 'width': 599, 'height': 1078, 'size': 0, 'duration': 0}, 'preview': {'width': 599, 'height': 1078, 'size': 0}}, 'source': {'source': 'https://url.com', 'width': 599, 'height': 1078, 'size': 0, 'duration': 0}, 'squarePreview': 'https://url.com', 'full': 'https://url.com', 'preview': 'https://url.com', 'thumb': 'https://url.com', 'files': {'preview': {'url': 'https://url.com'}}, 'videoSources': {'720': None, '240': None}}], 'canViewMedia': True, 'preview': [], 'fundRaising': {'target': 69, 'targetProgress': 79.98, 'presets': ['39.99']}}




HIGHLIGHT_EXAMPLE={'id': 89898, 'userId': 89898, 'title': 'Date me 🥺', 'coverStoryId': 89898, 'cover': 'https://url.com', 'storiesCount': 1, 'createdAt': '2023-02-18T01:39:00+00:00'}



ARCHIVED_POST_EXAMPLE={'responseType': 'post', 'id': 89898, 'postedAt': '2021-04-16T06:07:27+00:00', 'postedAtPrecise': '1618553247.000000', 'expiredAt': None, 'author': {'id': 89898, '_view': 'a'}, 'text': 'filming this from a new angle 😳 yall like it?', 'rawText': 'filming this from a new angle 😳 yall like it?', 'lockedText': False, 'isFavorite': False, 'canReport': True, 'canDelete': False, 'canComment': True, 'canEdit': False, 'isPinned': False, 'favoritesCount': 309, 'mediaCount': 1, 'isMediaReady': True, 'voting': [], 'isOpened': True, 'canToggleFavorite': True, 'streamId': None, 'price': None, 'hasVoting': False, 'isAddedToBookmarks': False, 'isArchived': True, 'isPrivateArchived': False, 'isDeleted': False, 'hasUrl': False, 'isCouplePeopleMedia': False, 'commentsCount': 2, 'mentionedUsers': [], 'linkedUsers': [], 'linkedPosts': [], 'tipsAmount': '$15', 'tipsAmountRaw': 15, 'media': [{'id': 89898, 'type': 'video', 'convertedToVideo': False, 'canView': True, 'hasError': False, 'createdAt': '2021-03-29T00:34:24+00:00', 'info': {'source': {'source': 'https://url.com', 'width': 720, 'height': 1280, 'size': 0, 'duration': 149}, 'preview': {'width': 720, 'height': 1280, 'size': 0}}, 'source': {'source': 'https://url.com', 'width': 720, 'height': 1280, 'size': 0, 'duration': 149}, 'squarePreview': 'https://url.com', 'full': 'https://url.com', 'preview': 'https://url.com', 'thumb': 'https://url.com', 'files': {'preview': {'url': 'https://url.com'}}, 'videoSources': {'720': 'https://url.com', '240': 'https://url.com'}}], 'canViewMedia': True, 'preview': []}

MESSAGES_DICT={'responseType': 'message', 'text': 'do you think your dick can handle me for over an hour?', 'giphyId': None, 'lockedText': False, 'isFree': False, 'price': 6.69, 'isMediaReady': True, 'mediaCount': 1, 'media': [{'id': 89898, 'canView': False, 'type': 'video', 'src': None, 'preview': None, 'thumb': None, 'locked': None, 'duration': 5468, 'hasError': False, 'videoSources': {'720': None, '240': None}, 'source': {'source': None}, 'info': {'source': {'width': 720, 'height': 1280, 'size': 0}, 'preview': {'width': 540, 'height': 960, 'size': 0}}}], 'previews': [], 'isTip': False, 'isReportedByMe': False, 'isCouplePeopleMedia': False, 'queueId': 89898, 'fromUser': {'id': 89898, '_view': 's'}, 'isFromQueue': True, 'canUnsendQueue': True, 'unsendSecondsQueue': 89898, 'id': 89898, 'isOpened': False, 'isNew': False, 'createdAt': '2023-04-14T11:50:17+00:00', 'changedAt': '2023-04-14T11:50:17+00:00', 'cancelSeconds': 89898, 'isLiked': False, 'canPurchase': True, 'canPurchaseReason': '', 'canReport': True, 'canBePinned': True, 'isPinned': False}



PAID_EXAMPLE={'responseType': 'message', 'text': 'Orgy', 'giphyId': None, 'lockedText': False, 'isFree': False, 'price': 19.99, 'isMediaReady': True, 'mediaCount': 1, 'media': [{'id': 89898, 'canView': True, 'type': 'video', 'src': 'https://url.com', 'preview': 'https://url.com', 'thumb': 'https://url.com', 'locked': None, 'duration': 1037, 'hasError': False, 'squarePreview': 'https://url.com', 'video': {'mp4': 'https://url.com'}, 'videoSources': {'720': 'https://url.com', '240': 'https://url.com'}, 'source': {'source': 'https://url.com'}, 'info': {'source': {'width': 1920, 'height': 1080, 'size': 0}, 'preview': {'width': 760, 'height': 428, 'size': 0}}}], 'previews': [], 'isTip': False, 'isReportedByMe': False, 'isCouplePeopleMedia': False, 'queueId': 89898, 'isCanceled': True, 'fromUser': {'id': 89898, '_view': 's'}, 'isFromQueue': True, 'canUnsendQueue': False, 'unsendSecondsQueue': 0, 'id': 89898, 'isOpened': True, 'isNew': False, 'createdAt': '2022-10-31T21:55:47+00:00', 'changedAt': '2022-10-31T21:55:47+00:00', 'cancelSeconds': 0, 'isLiked': False, 'canPurchase': False, 'canReport': True}


STORIES_EXAMPLE={'id': 89898, 'userId': 89898, 'isWatched': False, 'isReady': True, 'media': [{'id': 89898, 'type': 'photo', 'convertedToVideo': False, 'canView': True, 'hasError': False, 'createdAt': '2023-02-11T02:08:30+00:00', 'files': {'source': {'url': 'https://url.com', 'width': 1258, 'height': 1390, 'duration': 0, 'size': 0, 'sources': {'720': None, '240': None}}, 'thumb': {'url': 'https://url.com', 'width': 300, 'height': 300, 'size': 0}, 'preview': {'url': 'https://url.com', 'width': 960, 'height': 1061, 'size': 0, 'sources': {'w150': 'https://url.com'}}, 'squarePreview': {'url': 'https://url.com', 'width': 960, 'height': 960, 'size': 0, 'sources': {'w150': 'https://url.com', 'w480': 'https://url.com'}}}}], 'createdAt': '2023-04-14T00:19:53+00:00', 'question': None, 'canLike': True, 'isLiked': False}
