CONNECT_TIMEOUT = 100
POOL_CONNECT_TIMEOUT = 100
MAX_CONNECTIONS = 100
API_MAX_CONNECTION = 100
CHUNK_READ_TIMEOUT = 100
TOTAL_TIMEOUT = None
KEEP_ALIVE = 20
KEEP_ALIVE_EXP = 10
PROXY = None
PROXY_MOUNTS = None
PROXY_AUTH = None
maxChunkSize = 1024 * 1024 * 10
maxChunkSizeB = 1024 * 1024


REQ_SEMAPHORE_MULTI = 5
API_REQ_SEM_MAX = 70
SCRAPE_PAID_SEMS=10
SUBSCRIPTION_SEMS=5
API_REQ_CHECK_MAX=10
LIKE_MAX_SEMS=40
MAX_SEMS_BATCH_DOWNLOAD=12
MAX_SEMS_SINGLE_THREAD_DOWNLOAD=50



DOWNLOAD_RETRIES = 10
NUM_TRIES = 10
CHUNK_ITER = 10
OF_MIN = 10
OF_MAX = 20
OF_AUTH_MIN = 3
OF_AUTH_MAX = 10
LOGIN_NUM_TRIES = 3
MAX_REQUEST_WORKERS = 20
API_MAX_AREAS = 2
API_TIMEOUT_PER_TASKS = 35
API_REQUEST_THREADONLY = ["Windows", "Linux", "Darwin"]
