MAX_TIMELINE_INDIVIDUAL_SEARCH = 10
MAX_PINNED_INDIVIDUAL_SEARCH = 10
MAX_ARCHIVED_INDIVIDUAL_SEARCH = 10
MAX_MESSAGES_INDIVIDUAL_SEARCH = 10
MAX_STREAMS_INDIVIDUAL_SEARCH = 10
API_INDVIDIUAL_NUM_TRIES = 3
API_PAID_NUM_TRIES = 8
API_CHECK_NUM_TRIES = 10
API_MAX_AREAS = 2
# page must be 50 post, and 50 is a reasonable size for max number of pages
REASONABLE_MAX_PAGE = 50
MIN_PAGE_POST_COUNT = 50

# messages
REASONABLE_MAX_PAGE_MESSAGES = 80
API_NUM_TRIES = 10
API_LIKE_NUM_TRIES = 5
#
API_TIMEOUT_PER_TASK = 500
API_REQUEST_THREADONLY = ["Windows", "Linux", "Darwin"]
API_REQ_SEM_MAX = 12
API_REQ_CHECK_MAX = 12
