# .github/actions/retry-artifact-operation/action.yml
name: 'Retryable Artifact Operation (Fixed Attempts)'
description: 'Uploads or downloads artifacts with a fixed number of retry attempts.'

inputs:
  operation_type:
    description: 'Specify "upload" or "download".'
    required: true
    type: string
  name:
    description: 'Artifact name.'
    required: true
    type: string
  path:
    description: 'Paths for operation.'
    required: true
    type: string
  # Renamed to if_no_files_found (underscore) to avoid issues with YAML expressions
  if_no_files_found:
    description: 'For upload: warn, error, ignore.'
    required: false
    default: 'warn'
    type: string
  overwrite:
    description: 'For upload: true/false.'
    required: false
    default: 'true'
    type: boolean

runs:
  using: "composite"
  steps:
    # Attempt 1 (Initial Try)
    - name: Attempt 1 - ${{ inputs.operation_type }} artifact
      id: attempt_1 # Unique ID for this step
      # Dynamically choose upload-artifact or download-artifact
      uses: ${{ inputs.operation_type == 'upload' && 'actions/upload-artifact@v4' || 'actions/download-artifact@v4' }}
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }} # The path input
        # Conditionally add upload-specific inputs if operation_type is 'upload'
        ${{ inputs.operation_type == 'upload' && format('if-no-files-found: {0}', inputs.if_no_files_found) || '' }}
        ${{ inputs.operation_type == 'upload' && format('overwrite: {0}', inputs.overwrite) || '' }}
      continue-on-error: true # Allow this specific attempt to fail without stopping the composite action

    # --- Retry 1 (Attempt 2) ---
    - name: Delay before Attempt 2
      # Only run if the previous attempt failed
      if: ${{ steps.attempt_1.outcome == 'failure' }}
      run: |
        echo "Attempt 1 failed. Retrying in 10 seconds..." >&2
        sleep 10
      shell: bash
    - name: Attempt 2 - ${{ inputs.operation_type }} artifact
      id: attempt_2
      if: ${{ steps.attempt_1.outcome == 'failure' }} # Only run if the previous attempt failed
      uses: ${{ inputs.operation_type == 'upload' && 'actions/upload-artifact@v4' || 'actions/download-artifact@v4' }}
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        ${{ inputs.operation_type == 'upload' && format('if-no-files-found: {0}', inputs.if_no_files_found) || '' }}
        ${{ inputs.operation_type == 'upload' && format('overwrite: {0}', inputs.overwrite) || '' }}
      continue-on-error: true

    # --- Retry 2 (Attempt 3) ---
    - name: Delay before Attempt 3
      if: ${{ steps.attempt_2.outcome == 'failure' }}
      run: |
        echo "Attempt 2 failed. Retrying in 10 seconds..." >&2
        sleep 10
      shell: bash
    - name: Attempt 3 - ${{ inputs.operation_type }} artifact
      id: attempt_3
      if: ${{ steps.attempt_2.outcome == 'failure' }}
      uses: ${{ inputs.operation_type == 'upload' && 'actions/upload-artifact@v4' || 'actions/download-artifact@v4' }}
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        ${{ inputs.operation_type == 'upload' && format('if-no-files-found: {0}', inputs.if_no_files_found) || '' }}
        ${{ inputs.operation_type == 'upload' && format('overwrite: {0}', inputs.overwrite) || '' }}
      continue-on-error: true

    # --- Retry 3 (Attempt 4) ---
    - name: Delay before Attempt 4
      if: ${{ steps.attempt_3.outcome == 'failure' }}
      run: |
        echo "Attempt 3 failed. Retrying in 10 seconds..." >&2
        sleep 10
      shell: bash
    - name: Attempt 4 - ${{ inputs.operation_type }} artifact
      id: attempt_4
      if: ${{ steps.attempt_3.outcome == 'failure' }}
      uses: ${{ inputs.operation_type == 'upload' && 'actions/upload-artifact@v4' || 'actions/download-artifact@v4' }}
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        ${{ inputs.operation_type == 'upload' && format('if-no-files-found: {0}', inputs.if_no_files_found) || '' }}
        ${{ inputs.operation_type == 'upload' && format('overwrite: {0}', inputs.overwrite) || '' }}
      continue-on-error: true

    # --- Final Check: Determine if the overall composite action failed ---
    - name: Final Status Check
      # This step will explicitly fail the composite action if all attempts (1 to 4) were unsuccessful.
      if: |
        (steps.attempt_1.outcome != 'success') &&
        (steps.attempt_2.outcome != 'success' || steps.attempt_2.outcome == 'skipped') &&
        (steps.attempt_3.outcome != 'success' || steps.attempt_3.outcome == 'skipped') &&
        (steps.attempt_4.outcome != 'success' || steps.attempt_4.outcome == 'skipped')
      run: |
        echo "::error::Artifact operation for '${{ inputs.name }}' failed after all 4 attempts."
        exit 1
      shell: bash