MAXFILE_SEMAPHORE = 1000000
PATH_STR_MAX = 200
TABLE_STR_MAX = 100
SPACE_DOWNLOAD_MESSAGE = "Skipping download because space min has been reached"
DOWNLOAD_THREAD_MIN = 5
DOWNLOAD_SLEEP = 0
MAX_PROGRESS_BARS = 20
MIN_ADD_PROGRESS_BARS = 10
