MAXFILE_SEMAPHORE =None
PATH_STR_MAX = 200
TABLE_STR_MAX = 100
SPACE_DOWNLOAD_MESSAGE = "Skipping download because space min has been reached"
DOWNLOAD_THREAD_MIN = 5
DOWNLOAD_SLEEP = 0
MAX_PROGRESS_BARS = 20
MIN_ADD_PROGRESS_BARS = 10
SHOW_DL_CHUNKS=False
SHOW_DL_CHUNKS_LEVEL="Warning"
DOWNLOAD_NUM_TRIES=3
DOWNLOAD_NUM_TRIES_CHECK = 1

