preferences = "pref_config.py"
configPath = ".config/ofscraper"
configFile = "config.json"
authFile = "auth.json"
databaseFile = "models.db"
mainProfile = "main_profile"
requestAuth = "request_auth.json"
