STABLE_SLEEP_DURATION_LIKE=0
SLEEP_DURATION_LIKE_60=0
SLEEP_DURATION_LIKE_50=0
COMMON_MULTIPLE_SLEEP_DURATION_LIKE=0
DOUBLE_TOGGLE_SLEEP_DURATION_LIKE=0
SESSION_429_LIKE_INCREASE_SLEEP_TIME_DIF=0
SESSION_429_STARTER_VAL=0




# STABLE_SLEEP_DURATION_LIKE=5
# SLEEP_DURATION_LIKE_60=1
# SLEEP_DURATION_LIKE_50=30
# COMMON_MULTIPLE_SLEEP_DURATION_LIKE=40
# DOUBLE_TOGGLE_SLEEP_DURATION_LIKE=5
# SESSION_429_LIKE_INCREASE_SLEEP_TIME_DIF=30
# SESSION_429_STARTER_VAL=0


